#!/bin/bash
#### 2011.10.10 by TsengYia. ####
ORCL_BASE="/opt/oracle"
setenforcing 0 &> /dev/null
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
#### 1. 确认已安装必备的软件包 ##############################
echo "Install Required RPM Packages ..."
yum -y install binutils compat-libstdc++-33 compat-libstdc++ elfutils-libelf elfutils-libelf-devel gcc gcc-c++ glibc glibc glibc-common glibc-devel glibc-devel glibc-headers ksh libaio libaio libaio-devel libaio-devel libgcc libgcc libstdc++ libstdc++ libstdc++-devel make sysstat unixODBC unixODBC unixODBC-devel unixODBC-devel &> /dev/null
grep Santiago /etc/redhat-release &> /dev/null && (
  rpm -e ksh --nodeps &> /dev/null
  rpm -i support-files/pdksh*.rpm &> /dev/null
)
#### 2.创建必需的用户、组账号 ###############################
echo "Create Oracle's Groups and User, Directory ..."
grep oinstall /etc/group &> /dev/null || groupadd oinstall
grep dba /etc/group &> /dev/null || groupadd dba
grep oracle /etc/passwd &> /dev/null || useradd -g oinstall -G dba oracle
echo "pwd123" | passwd --stdin oracle &> /dev/null
#### 3. 创建数据库安装目录 ##################################
mkdir -p $ORCL_BASE
chown -R oracle:oinstall $ORCL_BASE
chmod -R 775 $ORCL_BASE
#### 4. 调整内核运行参数 ####################################
echo "Configure Kernel Parameters ..."
grep io-max-nr /etc/sysctl.conf &> /dev/null || echo 'fs.aio-max-nr = 1048576
fs.file-max = 6815744
#kernel.shmall = 2097152
#kernel.shmmax = 536870912
kernel.shmmni = 4096
kernel.sem = 250 32000 100 128
net.ipv4.ip_local_port_range = 9000 65500
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048586' >> /etc/sysctl.conf
sysctl -p &> /dev/null
#### 5. 调整用户会话限制 ####################################
echo "Configure Shell Parameters ..."
grep oracle /etc/security/limits.conf &> /dev/null || echo 'oracle           soft    nproc   2047
oracle           hard    nproc   16384
oracle           soft    nofile  1024
oracle           hard    nofile  65536' >> /etc/security/limits.conf
grep pam_limits.so /etc/pam.d/login &> /dev/null || echo 'session    required     pam_limits.so' >> /etc/pam.d/login
grep oracle /etc/profile &> /dev/null || echo 'if [ $USER = "oracle" ]; then
    ulimit -u 16384 -n 65536
fi' >> /etc/profile
#### 6. 配置Oracle用户环境 ##################################
echo "Configure User's Enviroment ..."
grep ORACLE ~oracle/.bash_profile &> /dev/null || echo "umask 022
export ORACLE_BASE=$ORCL_BASE
export ORACLE_SID=orcl
export DISPLAY=:0.0" >> ~oracle/.bash_profile
#### END ####################################################
